"""page model

Revision ID: 341a99d048bc
Revises: 
Create Date: 2023-03-27 21:58:34.291586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341a99d048bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_pages')
    # ### end Alembic commands ###
