"""pages

Revision ID: 6cdc5bcec25f
Revises: 
Create Date: 2023-03-30 13:36:00.077676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdc5bcec25f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('categories', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categories'], ['pages_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages_post_tag',
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['pages_posts.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['pages_tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_post_tag')
    op.drop_table('pages_posts')
    op.drop_table('pages_tags')
    op.drop_table('pages_categories')
    # ### end Alembic commands ###
